### ISSUE TITLE
Designing the asset inventory management system

### ISSUE THREAD

**Issue by admdan** [admdan/clarus#21]
#20 I will of course need to work on my Figma designs for this ~

**Comment by admdan** [comment]
So what I have now is a fully themed Bootstrap-based Asset Inventory Management System (AIMS) page. I started by including Bootstrap 5.3 and Bootstrap Icons in the <head> to make sure I had access to the core styles and icons like the brightness toggle or HDD symbol next to the title. Here's the import:

``` html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
```

I set up light and dark themes using the `data-bs-theme` attribute. This allows the page to dynamically respond to the theme with different background and text colors. I defined the themes like this:

``` css
:root[data-bs-theme="light"] {
  --bs-body-bg: #f8f9fa;
  --bs-body-color: #212529;
}
:root[data-bs-theme="dark"] {
  --bs-body-bg: #121212;
  --bs-body-color: #f8f9fa;
}
```
The body tag uses these variables for its background and text color, and I gave it a transition so it feels smooth:

``` css
body {
  background-color: var(--bs-body-bg);
  color: var(--bs-body-color);
  transition: background-color 0.3s ease, color 0.3s ease;
}
```
Then I made a theme toggle button in the top right of the header. When I click it, it switches between dark and light themes and updates the icon accordingly. Here's the button itself:

``` html
<button id="themeToggle" onclick="toggleTheme()" class="btn btn-sm btn-outline-secondary">
  <i class="bi bi-brightness-high-fill" id="themeIcon"></i>
</button>
```
The script for handling this looks like:

``` js
function toggleTheme() {
  const html = document.documentElement;
  const icon = document.getElementById('themeIcon');
  const next = html.getAttribute('data-bs-theme') === 'dark' ? 'light' : 'dark';
  html.setAttribute('data-bs-theme', next);
  icon.className = next === 'dark' ? 'bi bi-moon-stars-fill' : 'bi bi-brightness-high-fill';
  localStorage.setItem('theme', next);
}

```
The system remembers the selected theme using localStorage, and on page load it restores the correct theme:

``` js
document.addEventListener('DOMContentLoaded', () => {
  const savedTheme = localStorage.getItem('theme');
  if (savedTheme) {
    document.documentElement.setAttribute('data-bs-theme', savedTheme);
    document.getElementById('themeIcon').className =
      savedTheme === 'dark' ? 'bi bi-moon-stars-fill' : 'bi bi-brightness-high-fill';
  }
});
```
